"""initial schema

Revision ID: 0c41a8268ed0
Revises: 
Create Date: 2026-07-18 15:18:21.471381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c41a8268ed0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector's `vector` column type (used by playbook_embeddings below)
    # requires this extension to exist first.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('audit_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('clause_id', sa.String(), nullable=False),
    sa.Column('old_risk', sa.String(), nullable=False),
    sa.Column('new_risk', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_overrides_report_id'), 'audit_overrides', ['report_id'], unique=False)
    op.create_table('playbook_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clause_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('fallback_language', sa.String(), nullable=False),
    sa.Column('risk_if_absent', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_embeddings_clause_type'), 'playbook_embeddings', ['clause_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_playbook_embeddings_clause_type'), table_name='playbook_embeddings')
    op.drop_table('playbook_embeddings')
    op.drop_index(op.f('ix_audit_overrides_report_id'), table_name='audit_overrides')
    op.drop_table('audit_overrides')
    # ### end Alembic commands ###
