"""audit clause acceptances

Revision ID: fed1c9cb319f
Revises: ecd543768f1b
Create Date: 2026-07-30 13:09:53.595121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed1c9cb319f'
down_revision: Union[str, Sequence[str], None] = 'ecd543768f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The log now records acceptances as well as overrides. The server default
    # backfills existing rows with what they already were, so the column can be
    # NOT NULL on a table that is never rewritten.
    op.add_column('audit_overrides', sa.Column('action', sa.String(), server_default='override', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_overrides', 'action')
    # ### end Alembic commands ###
